name: sena_gestion_carnets
description: "Aplicación móvil de carnets virtuales para SENA"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.3
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
