name: sena_carnet_digital
description: "Aplicaci칩n m칩vil de carnets digitales para SENA"
publish_to: 'none' 
version: 1.0.0+1 

environment:
  sdk: '>=3.8.1 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0 
  barcode_widget: ^2.0.3
  image_picker: ^1.0.4
  postgres: ^2.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  crypto: ^3.0.6
  flutter_dotenv: ^5.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#00A859" 
  adaptive_icon_foreground: "assets/images/icon_foreground.png"

# Opciones de optimizaci칩n (opcional, para reducir tama침o)
flutter_build:
  modes:
    release:
      dartDefines:
        - "FLUTTER_BUILD_MODE=release"
      extraGenSnapshotOptions:
        - "--obfuscate"
        - "--strip"
